In [1]:
import os
import sys
import pandas as pd
import numpy as np
import glob
import time
import gget
import scipy
import matplotlib.patches as patches
from scipy.sparse import csr_matrix
import anndata as an
import scanpy as sc
from scipy.signal import find_peaks
import matplotlib.pyplot as plt
import seaborn as sns
import networkx as nx
import random
from importlib import reload
from sklearn.feature_extraction.text import TfidfVectorizer
import warnings
from itertools import combinations
from scipy.spatial.distance import pdist, squareform

import surprise as sup

"""WARNING: no warnings"""
warnings.filterwarnings("ignore")

source_path = os.path.abspath("../source/")
sys.path.append(source_path)
import centrality as central
import matrix
import utils as ut
import plotting as plt2

In [2]:
fpath = "/scratch/indikar_root/indikar1/shared_data/higher_order/transcription_clusters/singlecell_core_incidence_1000000_protien_coding_only.pkl"
df =  pd.read_pickle(fpath)
print(f"{df.shape=}")
df.head()

df.shape=(4420, 6370)

,o3b03:3e6dd122-d8f5-562f-86de-fc4e384a667a,o3b96:1c1ffd57-ddd5-46cd-9c32-1dfa892c18be,o3b96:0759fe0f-df87-42e6-96c9-698671d5a7e2,o3b96:375781eb-927e-45ee-9155-ab4052b430bb,o1b59:ec5db31e-c0ae-44c5-91e0-bc40f486a37f,o3b50:c4af0102-ded4-4b11-bbf8-cbfdc1c1ae29_1,o3b50:b2098de7-780c-5e25-aef7-fc2fd55a730d_1,o3b03:6efe764e-ad6c-419b-8173-5a2e393b975d,o3b50:7faebcef-ab2e-43ed-accf-6bc9acd1655a_1,o3b50:d216bf99-0efd-4cb9-8908-6b97fafb3710,...,o3b31:00bd62b4-fdcf-4933-81bc-9a7b2dc280ca,o1b54:9b7f1801-2d0a-4d8e-8dff-3331cc9ae865_2,o4b27:78e6b31b-535d-4369-9369-b35b2f0d2c14,o1b31:4088b82d-702d-464f-8b9f-6f8adc4a312d,o4b46:533deccf-b0e3-4ccf-9339-12ca025a5b62,o1b22:a992959f-ead4-4dd6-853a-8c4fb93bc864,o1b44:38e3c9e2-b4c9-5b67-99c4-4f998703f861_1,o3b71:94739dfb-5f52-4d4b-9195-41ecf186ed0f,o3b26:066b320c-18bc-4efa-8ecc-0f18e1cf010a,o1b05:628d946e-d517-4b88-830b-f25c1d38d1a1
Zfp354c,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Coro2b,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Grk5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Alpk3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Slc10a7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# most common genes

In [18]:
pdf = df.T.copy()
pdf = pdf.astype(bool).astype(int)
pdf['cell_id'] = pdf.index.str[:5]
pdf = pdf.groupby('cell_id').max()
print(f"{pdf.shape=}")
pdf.head()

pdf.shape=(312, 4420)

,Zfp354c,Coro2b,Grk5,Alpk3,Slc10a7,Esr1,Skp1,Cdh13,Xrcc4,Nfix,...,Polb,Cd207,Gm7876,Fgf12,Myom1,Slc45a1,Fnbp1,Fbxl2,Hs6st1,Caps2
cell_id,,,,,,,,,,,,,,,,,,,,,
o1b01,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
o1b02,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
o1b03,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
o1b04,0,0,0,1,0,0,0,0,0,0,...,0,1,0,1,0,0,0,0,0,0
o1b05,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
gdf = pdf.sum(axis=0).reset_index()
gdf.columns = ['gene_name', 'cell_count']
gdf = gdf.sort_values(by='cell_count', ascending=False)
gdf['percent'] = 100*(gdf['cell_count'] / pdf.shape[0])
print(gdf.head(10).to_string(index=False))

gene_name  cell_count   percent
    Gvin1         154 49.358974
    Crim1         150 48.076923
    Lrp1b         121 38.782051
    Pdcd1         105 33.653846
 Slc22a28         104 33.333333
 Cfap20dc          96 30.769231
  Vmn2r77          95 30.448718
   Lpgat1          82 26.282051
     Sars          77 24.679487
  Septin2          74 23.717949